RefactorChallange
Fajlix/SonyMZ1 pull request #11
Opened 2021-04-22 17:21 UTC by BQ-QB

Quick Refactor to delete unwanted class

2021-04-25 09:15 UTC, TJOCKochFIN reviewed
Looks good, I recognize from previous experience. But a lack of comments, comment what the class is for and some methods to make it clearer

2021-04-26 12:48 UTC, Wendaaj commented on app/src/main/java/com/example/sonymz1/Challenge.java
> +    public Challenge(String name, int mImageResource2, int mImageResource3) {
Hade varit nice om du döpte mImageResource2 och mImageResource3 till ngt annat så att man vet vad den är till för.

2021-04-26 12:50 UTC, Wendaaj requested changes
Som Viktor nämnde. Javadocs och tydligare variabelnamn som ex. i Challenge klassen.

2021-04-28 08:44 UTC, Wendaaj approved these changes
Veri niceee

2021-05-02 18:22 UTC, merged