add score page
Fajlix/SonyMZ1 pull request #26
Opened 2021-05-12 07:03 UTC by elinawahlstrom

2021-05-12 07:29 UTC, Wendaaj commented on app/src/main/java/com/example/sonymz1/AddingScorePage.java
> +public class AddingScorePage extends Fragment {
Javadocs missing

2021-05-12 07:33 UTC, Wendaaj requested changes

2021-05-12 07:33 UTC, Wendaaj commented on app/src/main/java/com/example/sonymz1/AddingScorePage.java
> +public class AddingScorePage extends Fragment {
Add javadocs

2021-05-14 09:32 UTC, TJOCKochFIN approved these changes

2021-05-14 13:49 UTC, BQ-QB approved these changes

2021-05-17 14:41 UTC, Wendaaj approved these changes

2021-05-17 14:57 UTC, merged